Timewarrior 1.7.0 (#10)

diff --git a/source/test/docker/opensuseleap b/source/test/docker/opensuseleap
--- a/source/test/docker/opensuseleap
+++ b/source/test/docker/opensuseleap
@@ -6,12 +6,13 @@ RUN zypper install -y \
            gcc-c++ \
            git \
            make \
+           man \
            python3 \
            python3-python-dateutil \
            ruby
 
-RUN gem install asciidoctor
-RUN update-alternatives --install /usr/bin/asciidoctor asciidoctor /usr/lib64/ruby/gems/2.5.0/gems/asciidoctor-2.0.12/bin/asciidoctor 10
+RUN gem install asciidoctor -v 2.0.15
+RUN update-alternatives --install /usr/bin/asciidoctor asciidoctor /usr/lib64/ruby/gems/2.5.0/gems/asciidoctor-2.0.15/bin/asciidoctor 10
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
 ENV TZ=Europe/Berlin
 
@@ -32,6 +33,6 @@ RUN make install
 
 # Setup tests
 WORKDIR /root/code/test/
-RUN make
+RUN make -j2
 
-CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version; exit $FAILED"]
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
